### ISSUE TITLE
Connection diagram?

### ISSUE THREAD

**Issue by Angel4o** [jvk0/ibutton-cloner#1]
Hi Ján V. Thanks for posting your project. I have an interest in repeating it. Is it possible to publish the connection diagram? Thanks in advance!

**Comment by jvk0** [comment]
Sure, here it is
(Not mine own drawing, but I'll let my friend know you said thanks)

![ibutton_diagram](https://user-images.githubusercontent.com/2332484/127614320-9c6274a6-abcf-47e9-bd1a-7657f5b16d8f.png)

But be aware that the particular LCD display we were using had a really iffy character set encoding (that was the reason why we needed to modify the hd44780 library), so you might be better off using something else.

**Comment by Angel4o** [comment]
Thank you very much for the quick and comprehensive answer!

Cheers

**Comment by jvk0** [comment]
No problem
If you have any other questions/issues, feel free to ask
